# Mod
mod_id = balm
mod_name = Balm
mod_author = BlayTheNinth
credits = BlayTheNinth
description = Abstraction Layer (but not really) for Blay's multiplatform mods
version = 26.3.0.0
group = net.blay09.mods
homepage=https://balm.twelveiterations.com
sources=https://github.com/TwelveIterations/Balm
issues=https://github.com/TwelveIterations/Balm/issues
discord = https://discord.gg/VAfZ2Nau6j
license = All Rights Reserved

# Publishing
curseforge_project_id = 531761
curseforge_environments = Client,Server
modrinth_project_id = MBAkmtvl
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Build
java_version = 25
neoforge_snapshot_url=https://prmaven.neoforged.net/NeoForge/pr3198
include_fabric=true
include_neoforge=false
include_forge=false

# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
