# Mod
mod_id=balm
version = 7.3.43
group=net.blay09.mods

# Publishing
curseforge_release_type=release
curseforge_project_id=531761
curseforge_forge_project_id=531761
curseforge_fabric_project_id=531761
modrinth_release_type=release
modrinth_project_id = MBAkmtvl
maven_releases = https://maven.twelveiterations.com/repository/maven-releases/
maven_snapshots = https://maven.twelveiterations.com/repository/maven-snapshots/

# Minecraft
minecraft_version = 1.20.1
minecraft_versions = 1.20,1.20.1
minecraft_version_range=[1.20,1.21)
java_version = 17

# Forge
forge_version = 47.3.27
forge_version_range=[46.0.0,)
forge_loader_version_range=[46,)
forge_mixins=true

# Fabric
fabric_version = 0.92.11+1.20.1
fabric_loader_version = 0.16.10

# Dependencies
kuma_version_range=[20.1.0,20.2.0)
kuma_version=20.1.12+1.20.1
jei_minecraft_version=1.19.2
jei_version=11.4.0.288
rei_version=10.0.581
wthit_version=8.16.1
jade_fabric_version=6106093
jade_forge_version=6106101
mixin_version=0.8.5
modmenu_version=7.2.2
theoneprobe_version=6106996
cloth_config_version=11.0.99

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

include_forge=true
include_fabric=true
