[versions]
minecraft = "26.3-snapshot-4"
neoForm = "26.3-snapshot-4-1"
neoForge = "26.2.0.0-beta"
forge = "64.0.4"
fabricApi = "0.155.1+26.3"
fabricLoader = "0.19.3"
kuma = "26.3.0.1-SNAPSHOT"
ftbUltimine = "26.1.0.1-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

neoForm = { module = "net.neoforged:neoform", version.ref = "neoForm" }
neoForge = { module = "net.neoforged:neoforge", version.ref = "neoForge" }
forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
fabricApi = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }

kumaCommon = { module = "net.blay09.mods:kuma-api-common", version.ref = "kuma" }
kumaFabric = { module = "net.blay09.mods:kuma-api-fabric", version.ref = "kuma" }
kumaNeoForge = { module = "net.blay09.mods:kuma-api-neoforge", version.ref = "kuma" }
kumaForge = { module = "net.blay09.mods:kuma-api-forge", version.ref = "kuma" }
ftbUltimineCommon = { module = "dev.ftb.mods:ftb-ultimine", version.ref = "ftbUltimine" }
ftbUltimineFabric = { module = "dev.ftb.mods:ftb-ultimine-fabric", version.ref = "ftbUltimine" }
ftbUltimineNeoForge = { module = "dev.ftb.mods:ftb-ultimine-neoforge", version.ref = "ftbUltimine" }

mixin = { module = "org.spongepowered:mixin", version = "0.8.7" }
mixinExtras = { module = "io.github.llamalad7:mixinextras-common", version = "0.5.2" }

vivecraftCommon = { module = "curse.maven:vivecraft-667903", version = "8320962" }
wthitCommon = { module = "mcp.mobius.waila:wthit-api", version = "mojmap-19.0.0" }
jeiCommon = { module = "mezz.jei:jei-26.1-common-api", version = "29.2.0.20" }
modMenu = { module = "maven.modrinth:modmenu", version = "18.0.0-alpha.8" }
trinketsUpdated = { module = "eu.pb4:trinkets", version = "4.1.0-beta.2+26.2" }
fabricPermissionsApi = { module = "me.lucko:fabric-permissions-api", version = "0.7.0" }
rebornEnergy = { module = "teamreborn:energy", version = "5.0.0" }
clothConfigNeoForge = { module = "me.shedaniel.cloth:cloth-config-neoforge", version = "26.1.154" }
clothConfigFabric = { module = "me.shedaniel.cloth:cloth-config-fabric", version = "26.1.154" }
configuredNeoForge = { module = "curse.maven:configured-457570", version = "7820635" }
configuredFabric = { module = "curse.maven:configured-457570", version = "7820636" }
jadeFabric = { module = "maven.modrinth:jade", version = "26.0.5+fabric" }
jadeNeoForge = { module = "maven.modrinth:jade", version = "26.0.6+neoforge" }
curios = { module = "top.theillusivec4.curios:curios-neoforge", version = "15.0.0-beta.1+26.1" }
theOneProbe = { module = "curse.maven:the-one-probe-245211", version = "6106996" }

[plugins]
fabricLoom = { id = "net.fabricmc.fabric-loom", version = "1.17-SNAPSHOT" }
modDevGradle = { id = "net.neoforged.moddev", version = "2.0.142" }
forgeGradle = { id = "net.minecraftforge.gradle", version = "[7,8)" }
forgeJarJar = { id = "net.minecraftforge.jarjar", version = "0.2.3" }
mixin = { id = "org.spongepowered.mixin", version = "0.7-SNAPSHOT" }
curseForgeGradle = { id = "net.darkhax.curseforgegradle", version = "1.1.26" }
modrinthMinotaur = { id = "com.modrinth.minotaur", version = "2.+" }
