plugins {
    id 'multiloader-common'
    alias libs.plugins.modDevGradle
}

neoForge {
    neoFormVersion = libs.neoForm.get().version
    accessTransformers {
        publish file("src/main/resources/META-INF/accesstransformer.cfg")
    }
}

dependencies {
    compileOnly libs.mixin
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

apply from: rootProject.file('repositories.gradle')
apply from: 'dependencies.gradle'

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
    commonGeneratedResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

sourceSets {
    generated {
        resources {
            srcDir 'src/generated/resources'
        }
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
    commonGeneratedResources sourceSets.generated.resources.sourceDirectories.singleFile
}
